# Generated by Django 6.0.3 on 2026-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
    ]
