# Generated by Django 6.0.3 on 2026-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage_owner_flashcard_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
